apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./manifest/production/namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
